[project]
name = "news-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx==0.28.1",
    "pandas==2.3.3",
    "pyarrow==21.0.0",
    "selectolax==0.4.0",
]
